### ISSUE TITLE
Failed to get device id from spotify

### ISSUE THREAD

**Issue by strandaster** [fondberg/spotcast#170]
Hi all,
many thanks to @fondberg for the great component. So I was able to manage the requirement that my kids are able to ask our google home minis to play a random album. They are using it since months in during the covid pandemic...

Since yesterday evening the spotcast component can't start any playback. I already restarted my home assistant instance and inserted new values for sp_dc and sp_key to be sure that the token is valid. No updates are made since last week.

Spotcast is build up a connection to my Google Home (I can hear the "bling") but then I got the message "Failed to get device id from spotify".

```
2021-03-23 08:08:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1860452328] Failed to get device id from Spotify
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 218, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 323, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1041, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 262, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 466, in _async_call_service_step
await self._async_run_long_action(service_task)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 428, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 218, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 323, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1041, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 262, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await self._hass.async_add_executor_job(handler.job.target, service_call)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/spotcast/__init__.py", line 296, in start_casting
spotify_device_id = spotify_cast_device.getSpotifyDeviceId(client)
File "/config/custom_components/spotcast/__init__.py", line 478, in getSpotifyDeviceId
raise HomeAssistantError("Failed to get device id from Spotify")
homeassistant.exceptions.HomeAssistantError: Failed to get device id from Spotify

```

Playback using open.spotify.com or the app is working without any issue on the chromecast devices.

Any hints?

Thanks,
Kai

**Comment by skipishere** [comment]
I'm having the same issue, was working fine yesterday morning but since yesterday evening it now errors with the same message your getting every time.

**Comment by mindtripper** [comment]
Getting the same as of this morning.
`2021-03-23 09:13:06 ERROR (SyncWorker_4) [custom_components.spotcast] No device with id "<id>" known by Spotify
2021-03-23 09:13:06 ERROR (SyncWorker_4) [custom_components.spotcast] Known devices: []
`

**Comment by dbaje** [comment]
It seems like Spotify changed their API. The device list returned doesn't contain the chrome cast for example. It only returns it if you are currently connected to said device

**Comment by provinzio** [comment]
Which means, that we have to get the device ids manually..? Sounds cumbersome, but I can't see a better way at the moment. I would love to know, how the app is handling this..

It's quite easy to get the device id over the [spotify web console](0
https://developer.spotify.com/console/get-users-available-devices/]. Just start the device with the app and run the API request.

**Comment by DONRozeboom** [comment]
I have the same issue, with both spotcast and the custom spotify card.

**Comment by strandaster** [comment]
@provinzio: In my web console, I got an empty list of devices. But I don't know how the api behaved before the api change.

**Comment by provinzio** [comment]
Cast devices are only shown, when they are triggered.

Activate spotcast/play and run the API again. It should show your device.

Kai G. ***@***.***> schrieb am Di., 23. März 2021, 15:58:

**Comment by Marcos-kp** [comment]
Same problem here...

**Comment by nolenjohan** [comment]
I have the same issue as described above, it have been working perfectly but now when choosing a CC Audio I hear the connecting sound from it but directly after I get this error message:
![Spotcast](https://user-images.githubusercontent.com/34334118/112265900-8c6ccb80-8c73-11eb-8c16-1b6841839df4.jpg)

**Comment by tcarlsen** [comment]
same

**Comment by peterson1190** [comment]
Same

**Comment by provinzio** [comment]
Why does everyone on github feel the urge to spam. Just click on the notification bell if you want to be alerted or say something useful..

**Comment by peceq** [comment]
> Cast devices are only shown, when they are triggered. Activate spotcast/play and run the API again. It should show your device.

still doesn't work, when i triggerred chromecast device appeared on API, i tried with different names but no results.

**Comment by provinzio** [comment]
Mhh... I can't say any other than it works for me... If these points doesn't help you, I have unfortunatly no idea. We should have a deeper look into `spotipy.Spotify.devices()` which is not part of this repo.

- Does your selected token from the [web api](https://developer.spotify.com/console/get-users-available-devices/) have the correct permission? It asks me which permissions it should have after I click `Get Token`
- Does your chromecast device make the "bling" sound?
- Hit the "Try it" button a few times.
- Does the API work at all for you? My desktop (with opened spotify) is always shown in the list.

**Comment by provinzio** [comment]
I found this in my Hassio error log

```
Logger: spotipy.client
Source: /usr/local/lib/python3.8/site-packages/spotipy/client.py:258
First occurred: 08:34:56 (1 occurrences)
Last logged: 08:34:56
HTTP Error for PUT to https://api.spotify.com/v1/me/player/play?device_id=<MY_DEVICE_ID> returned 403 due to Player command failed: Restriction violated
```

**Comment by arkane2002** [comment]
> Mhh... I can't say any other than it works for me... If these points don't help you, I have unfortunatly no idea. We should have a deeper look into `spotipy.Spotify.devices()` which is not part of this repo.
> 
> * Does your selected token from the [web api](https://developer.spotify.com/console/get-users-available-devices/) have the correct permission? It asks me which permissions it should have after I click `Get Token`
> * Does your chromecast device make the "bling" sound?
> * Hit the "Try it" button a few times after the bling.
> * Does the API work at all for you? My desktop (with opened spotify) is always shown in the list.
> 
> You might want to try my dirty fix [c6b2953](https://github.com/fondberg/spotcast/commit/c6b29531fb0836c7665a020c18fc33a99fba9dc3).

The dirty fix works perfectly on all the google home we have (each bedroom has a home mini used as an alarm clock with an automation + scheduler_card + spotcast).
Thank you for the dirty fix while waiting for a more logical solution

**Comment by kireque** [comment]
I can also confirm that the dirty fix solves the issue, for now.

**Comment by Maaxion** [comment]
The dirty fix works in-as-much as it allows playback again. But with the dirty fix in place the [spotify card](https://github.com/custom-cards/spotify-card) playback controls do not show up.

**Comment by provinzio** [comment]
Assumption: The spotify card is generated from the list of devices. Since list list is always empty, it won't show anything. (?)

**Comment by fillwe** [comment]
Same issue here, dirty fix solved it here as well (in the meantime)👍

**Comment by ludwigvdb** [comment]
Hi, Same here, i thought the dirty fix solved the problem but my devices ID don't stay for long in spotify API.
If something is already playing on my device launched from the app, i can launch anything else with spotcast. But if my device is idle for a moment. Spotcast return an error considering the ID isn't known by spotify. 
If i check on spotify web api, my devices is empty
Any idea why spotify doesn't keep my devices in memory ? is there any workaround ?
(Not exactly a issue with the dirty fix but if you have ideas :) )

**Comment by codetalker78** [comment]
I have the same issue too. Using spotcast with _device_name_ fails with this error in the logfile:
```
Logger: custom_components.spotcast
Source: custom_components/spotcast/__init__.py:474
Integration: Start Spotify on chromecast (documentation)
First occurred: 8:49:48 PM (3 occurrences)
Last logged: 8:57:10 PM

No device with id "<REDACTED>" known by Spotify
```
I then tried to use _spotify_device_id_ in the service call. This was working for the device id of the windows desktop spotify app, but failed with these two error messages for a chromecast audio device:

```
Logger: spotipy.client
Source: /usr/local/lib/python3.8/site-packages/spotipy/client.py:258
First occurred: March 24, 2021, 7:23:30 PM (5 occurrences)
Last logged: 9:06:21 PM

HTTP Error for PUT to https://api.spotify.com/v1/me/player/play returned 404 due to Player command failed: No active device found
HTTP Error for PUT to https://api.spotify.com/v1/me/player/play?device_id=<REDACTED> returned 404 due to Device not found`
```
and
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:259
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:06:15 PM (3 occurrences)
Last logged: 9:22:14 PM

[281473420678240] http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=<REDACTED>: Device not found, reason: None
[281473262000688] http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=<REDACTED>: Device not found, reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/play?device_id=173feeb594212d8ef1e14aadd6511b3a

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 [...]
  File "/config/custom_components/spotcast/__init__.py", line 307, in start_casting
    play(client, spotify_device_id, uri, random_song, repeat, shuffle, position)
  File "/config/custom_components/spotcast/__init__.py", line 259, in play
    client.start_playback(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 1706, in start_playback
    return self._put(
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 306, in _put
    return self._internal_call("PUT", url, payload, kwargs)
  File "/usr/local/lib/python3.8/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=173feeb594212d8ef1e14aadd6511b3a:
 Device not found, reason: None
```

**Comment by provinzio** [comment]
@codetalker78 entity_id with my dirty bugfix should work https://github.com/provinzio/spotcast/commit/c6b29531fb0836c7665a020c18fc33a99fba9dc3

**Comment by ludwigvdb** [comment]
> @codetalker78 entity_id with my dirty bugfix should work [provinzio@c6b2953](https://github.com/provinzio/spotcast/commit/c6b29531fb0836c7665a020c18fc33a99fba9dc3)

As i said before, it works if Spotify already knows the device. But for some reason, if nothing is play on thé device for half an hour, the device disapeared from Spotify API and we get error described by codetalker78. As soon as i "wake UP" the device with Spotify app, the dirty fix works again (device keep the same spotify_entity_id

**Comment by xabaras75** [comment]
I do not know if it can help to solve this problem.
in my cases I can launch the playlist from the spotify app and it is what I can see:


![image](https://user-images.githubusercontent.com/64804254/112729110-c7e4ef80-8f2a-11eb-9bbd-19c80b3100cd.png)

basically the names of the echo dot is correct in the standard media palyer card (you can see "Cucina") but not correct into the spotify card (there is a string of numbers...)

**Comment by mfabiani53** [comment]
Can someone please post the full __init__.py fixed file in raw format? I was not able to modify the original one...

**Comment by hmmbob** [comment]
https://raw.githubusercontent.com/provinzio/spotcast/c6b29531fb0836c7665a020c18fc33a99fba9dc3/custom_components/spotcast/__init__.py

**Comment by mfabiani53** [comment]
Many thanks!!!!

**Comment by reidkersey** [comment]
Just for clarity of people who might need this in the future. To implement the "dirty fix", edit the `__init__.py` file (found in `/config/custom_components/spotcast/__init__.py` and paste the contents of this file ([__init__.py](https://raw.githubusercontent.com/provinzio/spotcast/c6b29531fb0836c7665a020c18fc33a99fba9dc3/custom_components/spotcast/__init__.py)), replacing all that is currently there. Save and reboot HA.

**Comment by fondberg** [comment]
Hello everybody.

Open source is great and free which in the case of just one person going the work (me) can lead to situations where during periods of sick leave or pressing matters elsewhere (work) thiings piles up.


I would urge you to put efforts into trying to help out by fixing things through pull requests rather than say something is broken several times and come up with arbitrary non version controlled patches.

I too noticed this is broken and if no one chips in i will try and fix it when i have time

**Comment by justincrosby** [comment]
FYI all, after updating to HA 2021.4.0 and applying #173 to fix the breaking changes I'm no longer encountering this issue. I think that PR might be the way to go.

**Comment by KapJI** [comment]
@justincrosby well, that's because this PR includes this "dirty fix" 😀

**Comment by pergolafabio** [comment]
I applied that temp fix, but i don't see any cast devices anymore now when using the spotify Lovelace card

**Comment by Electronlibre2012** [comment]
> 
> 
> Hello everybody.
> 
> Open source is great and free which in the case of just one person going the work (me) can lead to situations where during periods of sick leave or pressing matters elsewhere (work) thiings piles up.
> 
> I would urge you to put efforts into trying to help out by fixing things through pull requests rather than say something is broken several times and come up with arbitrary non version controlled patches.
> 
> I too noticed this is broken and if no one chips in i will try and fix it when i have time

take care @fondberg

**Comment by fondberg** [comment]
Fixed together with core PRs. Help me upvote them (links in this PR) https://github.com/fondberg/spotcast/pull/176

**Comment by frenck** [comment]
@fondberg Asking for upvoting a PR doesn't change anything. Please don't. Thanks 👍

**Comment by fondberg** [comment]
@french i am sorry. I this is generally the way in other open source projects but i hear you in HA. 
Again sorry and people stop upvote!

**Comment by fondberg** [comment]
Fixed in https://github.com/fondberg/spotcast/releases/tag/v3.5.2. Help me test that release.

**Comment by xabaras75** [comment]
Now Ha give no error after the update. But I still see the echo dot not with their own name but with an alphanumeric string.
The only thing I ca see properly, is the group of echo dot defined as "casa" that male me spread the music on all the echo dot.
Many tks for your effort in updating this really useful integration. 
![Screenshot_2021-04-11-20-51-38-820_io homeassistant companion android](https://user-images.githubusercontent.com/64804254/114317323-cd842d00-9b07-11eb-80cd-584aa007b143.jpg)

**Comment by fondberg** [comment]
@xabaras75 enable debug and open a new issue. This issue is closed

**Comment by ontaptom** [comment]
@ludwigvdb by any chance did you find a solution to your issue with 'devices disappearing'?

**Comment by ludwigvdb** [comment]
> @ludwigvdb by any chance did you find a solution to your issue with 'devices disappearing'?

Hi, I didn't find any direct solution for this issue, BUT with the last HA update and the last spotcast update everything works fine again :)
(NB : SPOTIFY plugin is now necessary for spotcast to work)

**Comment by Chacsam** [comment]
Hi all,

I am having this issue for a week now.
I have a script starting with a spotcast.start to wake me up nicely that has been running great for months but not since last week:  it stops due to "Failed to get device id from Spotify"

Strangely enough, when I restart the script manually a couple minutes later, it works fine again.
I have updated my keys to be sure, but that didn't help.

Anyone else with the isuue?

**Comment by spyfly** [comment]
> Hi all,
> 
> I am having this issue for a week now. I have a script starting with a spotcast.start to wake me up nicely that has been running great for months but not since last week: it stops due to "Failed to get device id from Spotify"
> 
> Strangely enough, when I restart the script manually a couple minutes later, it works fine again. I have updated my keys to be sure, but that didn't help.
> 
> Anyone else with the isuue?

Same issue here. It seems like the first call which fails with an error wakes up the Chromecast and opens the Spotify App. Now Spotcast is able to retrieve the device id in the next call and it will start playing. I managed to make it work with the workaround seen below:
```
action:
  - service: spotcast.start
    continue_on_error: true
    data:
      uri: ***
      entity_id: ***
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: spotcast.start
    data:
      entity_id: ***
      uri: ***
      force_playback: true
      random_song: true
      shuffle: true
      start_volume: 100
```

**Comment by Chacsam** [comment]
Thanks, I'll try that

**Comment by CubicrootXYZ** [comment]
I am encountering this issue too, I am on version `3.6.29`. 

What I am seeing is that the first call fails but the second one will work. 

The error is:

```
2022-07-26 20:35:25 ERROR (SyncWorker_4) [custom_components.spotcast.spotcast_controller] No device with id "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" known by Spotify
2022-07-26 20:35:25 ERROR (SyncWorker_4) [custom_components.spotcast.spotcast_controller] Known devices: [{'id': 'bbbbbbbbbbbbbbbbbbbbbbbbbbb', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'bbbbbb', 'type': 'Smartphone', 'volume_percent': 100}, {'id': 'cccccccccccccc', 'is_active': True, 'is_private_session': False, 'is_restricted': False, 'name': 'ccccccccccccc', 'type': 'CastAudio', 'volume_percent': 32}]
2022-07-26 20:35:25 ERROR (MainThread) [homeassistant.components.script.spotify_playback] Spotify: Start Playback: Error executing script. Error for call_service at pos 1: Failed to get device id from Spotify
2022-07-26 20:35:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548068099552] Failed to get device id from Spotify
```

Any chance we might get a retry into the addon if the call to spotify failed the first time? 

@fondberg I think this issue should be opened again.

**Comment by Maaxion** [comment]
@CubicrootXYZ Your issue is the same as https://github.com/fondberg/spotcast/issues/334

**Comment by Jaykurb** [comment]
I've been using the 'Script to resume Google Cast devices after they have been interrupted by any action]' found at (https://community.home-assistant.io/t/script-to-resume-google-cast-devices-after-they-have-been-interrupted-by-any-action/383896) the https://community.home-assistant.io/t/script-to-resume-google-cast-devices-after-they-have-been-interrupted-by-any-action/383896/443 but It has stopped working recently. 

The author of the script has identified the issue is most likely spotcast as the script gives the error:
`"error": "Failed to get device id from Spotify"`

Any ideas how to resolve this please?

**Comment by spyfly** [comment]
It is being worked on: https://github.com/fondberg/spotcast/pull/339

**Comment by herrkaefer** [comment]
> > Hi all,
> > I am having this issue for a week now. I have a script starting with a spotcast.start to wake me up nicely that has been running great for months but not since last week: it stops due to "Failed to get device id from Spotify"
> > Strangely enough, when I restart the script manually a couple minutes later, it works fine again. I have updated my keys to be sure, but that didn't help.
> > Anyone else with the isuue?
> 
> Same issue here. It seems like the first call which fails with an error wakes up the Chromecast and opens the Spotify App. Now Spotcast is able to retrieve the device id in the next call and it will start playing. I managed to make it work with the workaround seen below:
> 
> ```
> action:
>   - service: spotcast.start
>     continue_on_error: true
>     data:
>       uri: ***
>       entity_id: ***
>   - delay:
>       hours: 0
>       minutes: 0
>       seconds: 10
>       milliseconds: 0
>   - service: spotcast.start
>     data:
>       entity_id: ***
>       uri: ***
>       force_playback: true
>       random_song: true
>       shuffle: true
>       start_volume: 100
> ```

Nice workaround! Since the following playings are likely to be fine, it seems nicer to have a condition check of "playing" before the second try, so that if the first playing is good it doesn't go with another try. Also I feel 10 sec waiting could be longer than enough. My update looks like:

```
action:
  - service: spotcast.start
    continue_on_error: true
    data:
      entity_id: ***
      uri: ***
      force_playback: true
      random_song: true
      shuffle: true
      start_volume: 100
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - condition: not
    conditions:
      - condition: state
        entity_id: ***
        state: playing
  - service: spotcast.start
    data:
      entity_id: ***
      uri: ***
      force_playback: true
      random_song: true
      shuffle: true
      start_volume: 100
```

**Comment by GraysonCAdams** [comment]
@herrkaefer  I found a potentially better solution than timing things... do a loop until Spotify is playing, and use the `continue_on_error: true` to prevent an uncaught exception / failed automation.

```
alias: Play Music
sequence:
  - repeat:
      until:
        - condition: state
          entity_id: media_player.apartment
          state: playing
      sequence:
        - service: spotcast.start
          continue_on_error: true
          data:
            device_name: Apartment
            uri: "spotify:playlist:xxx"
        - delay:
            hours: 0
            minutes: 0
            seconds: 2
            milliseconds: 0
mode: single
icon: mdi:music
```

**Comment by herrkaefer** [comment]
@GraysonCAdams This is better if it works for you. But the network can be slow or even down and the forever trying could have some potential issue. Also the second try seems to be always working. So the slow and try-twice version is good enough for me 😄
