### ISSUE TITLE
Spotcast Call-service error. http status: 404, code:-1 Device not found

### ISSUE THREAD

**Issue by twangraus** [fondberg/spotcast#346]
# Bug Ticket

## Describe the bug

* [X] Using latest version of spotcast
* [X] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [X] I have Spotify Premium
* [X] I am using multiple accounts
* [X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see README)
* [ ] I'm attaching relevant logs with level debug for component spotcast (see README)
* [X] I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: [HA_OS]
 - HA version: [2022.8.6]
 - spotcast version: [V3.6.29]

## Configuration
spotify:
  client_id: XXXX
  client_secret: XXXX

spotcast:
  sp_dc: XXXXX
  sp_key: XXXXXX
  country: NL
  accounts:
    jennifer:
      sp_dc: XXXXXX
      sp_key: XXXXX

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

## Additional context
- Using in NodeRed
- Error in nodered: Call-service error. http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play?device_id=cab8a21e10b52899d538f8cbd312d56a:
 Device not found, reason: None

When URL pasted in browser:
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}

When searching for spotify connect devices, as described in spotcast manual, only devices are found which are "playing".

**Comment by fcusson** [comment]
@twangraus the URL in browser that's normal because you're pasting a POST request, you must go by CURL and provide a token header to troubleshoot the link.
Your problem seems to be the same as the #334 should resolve the issue you have with device not found error. I have been daily driving the version without any regression problem for almost 2 weeks now. The fix should be part of 3.7.0 which we are drafting at the moment.

**Comment by twangraus** [comment]
> @twangraus the URL in browser that's normal because you're pasting a POST request, you must go by CURL and provide a token header to troubleshoot the link. Your problem seems to be the same as the #334 should resolve the issue you have with device not found error. I have been daily driving the version without any regression problem for almost 2 weeks now. The fix should be part of 3.7.0 which we are drafting at the moment.

Thank you for your reply. Even with the temporary fix of calling the service twice in a row, the issue remains. Ill try some other things, and keep on waiting for a fix in a new release.

**Comment by twangraus** [comment]
The property "device_name" seems to be the only one of the 3 options which does not give the following error. Still need to call the spotcast service twice to make it work

**Comment by fcusson** [comment]
This is probably corrected in the new version 3.6.30, can you please update and validate if the problem is resolved

**Comment by madAndroid** [comment]
Confirmed to be working, thanks very much
