### ISSUE TITLE
Error when start on chromecast: KeyError: 'deviceID'

### ISSUE THREAD

**Issue by xmow49** [fondberg/spotcast#398]
# Bug Ticket

## Describe the bug

When I execute `spotcast.start` on my chromecast `Cuisine`, Spotify is launched, I have the logo on the screen, but after that, no music.

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [x] Using latest version of spotcast
* [x] Using latest stable version of Home Assistant
* [x] I have setup the Spotify integration in Home Assistant
* [x] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [x] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: HA_OS
 - HA version: 2023.8.4
 - spotcast version: 3.7.0

## Configuration

````yaml
spotcast:
  sp_dc: !secret dorian_sp_dc
  sp_key: !secret dorian_sp_key
````

## Service Call

If relevant, provide a `yaml` of the service call or explain the action taken to replicate the issue.

````yaml
service: spotcast.start
data:
  limit: 20
  force_playback: false
  random_song: false
  repeat: "off"
  shuffle: false
  offset: 0
  ignore_fully_played: false
  device_name: Cuisine

````

## Logs

* normal

````log
2023-08-28 18:28:53.826 ERROR (Thread-12) [pychromecast.socket_client] [Cuisine(192.168.2.33):8009] Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from 720cd6a6-a540-4ffb-9a6a-2f28bdab4ecd to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_video', 'brandDisplayName': 'google', 'modelDisplayName': 'Chromecast_Tv', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb71494ea994202cb473eae7', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pychromecast/socket_client.py", line 719, in _route_message
handled = handler.receive_message(message, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotify_controller.py", line 47, in receive_message
self.device = data["payload"]["deviceID"]
~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'deviceID'
2023-08-28 18:29:04.775 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Timeout when waiting for status response from Spotify app
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2018, in _execute_service
return await self._hass.async_add_executor_job(target, service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotcast_controller.py", line 252, in get_spotify_device_id
spotify_cast_device.startSpotifyController(access_token, expires)
File "/config/custom_components/spotcast/spotcast_controller.py", line 95, in startSpotifyController
sp.launch_app()
File "/config/custom_components/spotcast/spotify_controller.py", line 104, in launch_app
raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
2023-08-28 18:29:04.796 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547346856128] Error handling message: Unknown error (unknown_error) Dorian from 192.168.1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 716, in handle_execute_script
response = await script_obj.async_run(msg.get("variables"), context=context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
return await asyncio.shield(run.async_run())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
return long_task.result()
^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2018, in _execute_service
return await self._hass.async_add_executor_job(target, service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotcast_controller.py", line 252, in get_spotify_device_id
spotify_cast_device.startSpotifyController(access_token, expires)
File "/config/custom_components/spotcast/spotcast_controller.py", line 95, in startSpotifyController
sp.launch_app()
File "/config/custom_components/spotcast/spotify_controller.py", line 104, in launch_app
raise LaunchError(
pychromecast.error.LaunchError: Timeout when waiting for status response from Spotify app
````

## Additional context

I opened a Spotify on web browser, ran the service; but the device didn't appear on the device list. Only on the windows app I can view it.
When pychromecast is called we can see an error at
``` 
self.device = data["payload"]["deviceID"]
```
I don't know what to do now.

**Comment by DanDixon** [comment]
I'm also seeing this problem (started about 8 hours ago)

I am able to start Spotify on my chromcast devices by selecting the device in the Spotify App (but doesn't work if I start it from HomeAssistant)

From my logs
`
Error executing script. Unexpected error for call_service at pos 1: Timeout when waiting for status response from Spotify app
10:01:07 AM – (ERROR) Script (custom integration) - message first occurred at 9:55:28 AM and shows up 2 times

[Everywhere(192.168.1.74):32052] Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from 8465b09f... to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Chromecast_Audio', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb...', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
10:00:56 AM – (ERROR) Spotcast (custom integration) - message first occurred at 9:55:17 AM and shows up 6 times
`

**Comment by tech-kev** [comment]
I noticed the same problem about 13 hours ago.

Like @DanDixon, I can select and play music on my Chromecast device via the Spotify app, but not via Spotcast from HomeAssistant.

**Comment by Joakim-T** [comment]
> I'm also seeing this problem (started about 8 hours ago)
> 
> I am able to start Spotify on my chromcast devices by selecting the device in the Spotify App (but doesn't work if I start it from HomeAssistant)
> 
> From my logs
> 
> ```
> Error executing script. Unexpected error for call_service at pos 1: Timeout when waiting for status response from Spotify app
> 10:01:07 AM – (ERROR) Script (custom integration) - message first occurred at 9:55:28 AM and shows up 2 times
> 
> [Everywhere(192.168.1.74):32052] Exception caught while sending message to controller SpotifyController: Message urn:x-cast:com.spotify.chromecast.secure.v1 from 8465b09f... to sender-0: {'type': 'getInfoResponse', 'payload': {'version': '2.9.0', 'publicKey': 'empty', 'remoteName': 'Spotify on Cast', 'deviceType': 'cast_audio', 'brandDisplayName': 'google', 'modelDisplayName': 'Chromecast_Audio', 'libraryVersion': '5.30.3', 'resolverVersion': '1', 'groupStatus': 'NONE', 'deviceAPI_isGroup': False, 'tokenType': 'accesstoken', 'clientID': 'd7df0887fb...', 'productID': 0, 'scope': 'streaming', 'availability': '', 'spotifyError': 0, 'status': 101, 'statusString': 'OK'}}
> 10:00:56 AM – (ERROR) Spotcast (custom integration) - message first occurred at 9:55:17 AM and shows up 6 times
> ```

Same here.
Reinstalled Spotify and Spotcast integrations and got new keys.
No change.

**Comment by cjborchert** [comment]
I also have the same recurrence since yesterday evening. I tried the workarounds here again #365 however that indeed yielded a deviceId error as shown below:

`Logger: homeassistant
Source: custom_components/spotcast/spotcast_controller.py:135
Integration: Spotcast ([documentation](https://github.com/fondberg/spotcast), [issues](https://github.com/fondberg/spotcast/issues))
First occurred: 21:55:38 (1 occurrences)
Last logged: 21:55:38

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 596, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2018, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/__init__.py", line 221, in start_casting
    spotify_device_id = spotcast_controller.get_spotify_device_id(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 253, in get_spotify_device_id
    return spotify_device_id
                            ^
  File "/config/custom_components/spotcast/spotcast_controller.py", line 135, in getSpotifyDeviceId
homeassistant.exceptions.HomeAssistantError: Failed to get device id from Spotify`

**Comment by fcusson** [comment]
checked and seems to be a dependency issue. Spotify integration in Home Assistant doesn't report information anymore

**Comment by fcusson** [comment]
Found the problem, `deviceID` is no longer part of the reply message. We have to find a way to get that information in another way

**Comment by DanDixon** [comment]
Thank you so much for your work on this.

I use this integration many times each (averaging about 7 hours of music play every day over this last week) and just thank you for creating and maintaining this. I am so appreciative of your efforts ✨

**Comment by fcusson** [comment]
Just found a workaround for the moment. The only part broken is the ability to find the device id based on the entity_name in Home Assistant. Which means, it is possible to make the call with the spotify_id directly.

Spotify just reinstated there api console on the developper site. It is possible to request the available devices with [this link](https://developer.spotify.com/documentation/web-api/reference/get-a-users-available-devices).

I tested and I am able to play media using the spotify_id directly. I'll work on a way to repair the entity_name to device_id method.

**Comment by quincarter** [comment]
i noticed that the `sp_dc` and `sp_key` are no longer available in the cookies. I don't know if this will also affect this integration or related to this issue.

**Comment by teek541** [comment]
I thought I did something wrong.

Literally just got my music dashboard up and working the other night based on this link:
https://community.home-assistant.io/t/using-your-spotify-account-in-a-ha-dashboard-to-select-speakers-and-broadcast/487300

Then today I was getting timeout errors.  Do the device ID's ever change?  If not, can I just plug those in as static entries or should I wait for a better workaround?

Thanks for building/maintaining this integration.  One of the best ones on my HA server!

**Comment by wautersj** [comment]
It seems it has been fixed already at the side of Spotify. My flows all work again!
Anyone to confirm?

<img width="594" alt="Screenshot 2023-08-29 at 11 21 33" src="https://github.com/fondberg/spotcast/assets/4070167/49d3c12c-68de-4109-8d6f-0a7f2d153f71">

**Comment by fjeddy** [comment]
Noticing the same... Music won't play on any Google device, not just Chromecast. If I open the Spotify app and select the speaker I want, then I can control playlists etc through Home Assistant.

**Comment by cjborchert** [comment]
I’m still having the same issue without change from yesterday. However I did notice unreliable casting start from the Spotify mobile app as well. Took me a few attempts to get it going from the Spotify mobile app this morning.

**Comment by fcusson** [comment]
@wautersj no still broken, Spotify changed there api response, so we don't have access to the device I'd from where we used to. We need to find an alternate  way of finding the Spotify Device.

**Comment by wautersj** [comment]
@cjborchert @fcusson Correct. I found out just now why did suddenly worked for me.

If you once (with the spotify app for example) recently (as last used device) targeted the same target device as used in the node-red flows or ha automations, it still works. But when you target an other device in your flows or automations, using device name, it's still broken, and times out.

So it was a false positive. Thanks for pointing that out!
I live the integration, so hopefully some great minds come to a fitting solution.

**Comment by teek541** [comment]
Is it possible to get a list of devices on an account?  And do the device IDs change?  We could create a local list of device IDs with a selection helper or flow variables, right?

Sorry, still new to all this, I'm understanding the logic flows but learning the code and specifics behind how to do stuff.

**Comment by wautersj** [comment]
You could retrieve the device id's, using the API. But thats a wee bit more technical.

It's just so that the API of Spotify changed. I had to update the AppStore app to be able to smoothly cast to my google cast devices again. So I'm guessing the maintainers will update the integration as well.

**Comment by aliaghil** [comment]
I also having the same issue, any workaround?

**Comment by JacekJI** [comment]
I Think i have the same isue, from yesterday its inpossible to play spotify playlist ftom ha (mini media player. 
![inbound3089961916286189156](https://github.com/fondberg/spotcast/assets/120251550/1920dc00-146d-4fba-bdea-10409593cdd4)

**Comment by chasebolt** [comment]
having this issue. i queried `https://api.spotify.com/v1/me/player/devices` to see what returned and it shows none of my chromecast devices at home. i believe this is related to my issue.

**Comment by techtim89** [comment]
Chiming in also...  Same issue as everyone else.  Bummer....

**Comment by theepicsaxguy** [comment]
Yes same issue for new aswell


Med Vänliga Hälsningar

Benjamin Sandén

E: ***@***.******@***.***>



________________________________

**Comment by fcusson** [comment]
> having this issue. i queried `https://api.spotify.com/v1/me/player/devices` to see what returned and it shows none of my chromecast devices at home. i believe this is related to my issue.

@chasebolt this is normal Chromecast needs to be actively connected to spotify to show up in the API, Spotify API has no awareness of your local network devices that aren't actively in use.

**Comment by chasebolt** [comment]
bummer well back to the drawing board on this issue.

**Comment by oshriphoto** [comment]
It seems that this is a problem that appears to many users, does anyone have a solution to this problem? Is the developer of the plugin in the group and reading the errors? Maybe he can respond and say if it is in treatment or not?

**Comment by stoffus** [comment]
> > having this issue. i queried `https://api.spotify.com/v1/me/player/devices` to see what returned and it shows none of my chromecast devices at home. i believe this is related to my issue.
> 
> @chasebolt this is normal Chromecast needs to be actively connected to spotify to show up in the API, Spotify API has no awareness of your local network devices that aren't actively in use.

Sorry but this just sounds odd to me, but maybe I don't fully understand the functionality here. What do you mean with "actively in use"? The device obviously won't be in use the first time we initiate playback?

**Comment by TheFes** [comment]
@oshriphoto 
@fcusson is a frequent contributor of this integration, and actively posting in the thread. He is also assigned to this issue.
However if Spotify is not sharing necessary data anymore in their API, it might be difficult to solve.

**Comment by Joakim-T** [comment]
How does this project solve it?
https://github.com/music-assistant/hass-music-assistant

I guess since it requires a server that is always running it is always aware of what cast Devices are available? 
Tested and I can cast Spotify if i use it.

**Comment by zivgin** [comment]
Tracking this issue. i also effected by this.

**Comment by reganerasmus** [comment]
Following... I spent a good portion of the day reinstalling all the Spotify elements, glad to see I wasn't going crazy.

**Comment by mindtripper** [comment]
It’s a known issue. Install the latest beta . Restart HA. Then you can add it successfully.Been there, done that :)On 31 Aug 2023, at 14:43, oshriphoto ***@***.***> wrote:﻿
It is not possible to install it from the integrations this error appears:
: 500 Internal Server Error Server got itself in trouble

**Comment by mindtripper** [comment]
> How does this project solve it? https://github.com/music-assistant/hass-music-assistant
> 
> I guess since it requires a server that is always running it is always aware of what cast Devices are available? Tested and I can cast Spotify if i use it.

Works quite well the hours I've tested so far.
Looks like a decent and well-maintained alternative.
Only thing I'm missing is multiple accounts and choosing which to use when casting. This feature is actively being developed.

**Comment by Joakim-T** [comment]
> > How does this project solve it? https://github.com/music-assistant/hass-music-assistant
> > I guess since it requires a server that is always running it is always aware of what cast Devices are available? Tested and I can cast Spotify if i use it.
> 
> Works quite well the hours I've tested so far. Looks like a decent and well-maintained alternative. Only thing I'm missing is multiple accounts and choosing which to use when casting. This feature is actively being developed.

Yes but I hope this project can find some inspiration there and maybe a solution to this problem.

**Comment by chasebolt** [comment]
ok i got a workaround for now.

step1: play something from spotify on the device you want working
step2: goto https://developer.spotify.com/documentation/web-api/reference/get-a-users-available-devices and click "Try it" for the endpoint `https://api.spotify.com/v1/me/player/devices`. this should output json and provide you the `id` for the device you are playing spotify on.
step3: when calling spotcast provide `spotify_device_id` with `id` that you copied. there is no need to pass the `entity_id` to the service call.

**Comment by Banthaf0dder** [comment]
> > > having this issue. i queried `https://api.spotify.com/v1/me/player/devices` to see what returned and it shows none of my chromecast devices at home. i believe this is related to my issue.
> > 
> > 
> > @chasebolt this is normal Chromecast needs to be actively connected to spotify to show up in the API, Spotify API has no awareness of your local network devices that aren't actively in use.
> 
> Sorry but this just sounds odd to me, but maybe I don't fully understand the functionality here. What do you mean with "actively in use"? The device obviously won't be in use the first time we initiate playback?
> 
> @fcusson Which component is responsible for publishing the Chromecast device as an available Spotify device?

That is the whole point of Spotcast. Normally you can't cast to idle chromecast devices because Spotify doesn't know they exist so they have no ID. Spotcast gets them connected so Spotify can give them an ID, then gets the ID, then starts casting.

**Comment by Coxeroni** [comment]
There seems to be a general degradation in Spotify's service as casting to Google Cast device also works much worse when casting from the Android Spotify app.
The cast either does not work at all or only after several attempts. Additionally, the device is renamed to "Spotify on cast" while doing the casting.

So maybe this is a bug that needs fixing on Spotify's side? Just speculating...

**Comment by clowncracker** [comment]
Following!

**Comment by jboesh** [comment]
Also following, experience the same issue

**Comment by madAndroid** [comment]
I wonder if this is related, but at the same time this started happening, when I cast to a Chromecast speaker group, even from the Spotify desktop app, the state of the related Chromecast devices is not updated properly in Home Assistant.. all the devices in the group show `idle` as their state, instead of showing playing, and the details of the stream. Seems Google adjusted something in speaker groups in Google Home as well - can anyone else confirm this behaviour? I don't see any related issues for Cast devices, but it might be related to this same issue.

**Comment by TheFes** [comment]
@madAndroid I noticed this behavior some time ago already. I had add some stuff in my resume script to work with this change

**Comment by relic664** [comment]
> > How does this project solve it? https://github.com/music-assistant/hass-music-assistant
> > I guess since it requires a server that is always running it is always aware of what cast Devices are available? Tested and I can cast Spotify if i use it.
> 
> Works quite well the hours I've tested so far. Looks like a decent and well-maintained alternative. Only thing I'm missing is multiple accounts and choosing which to use when casting. This feature is actively being developed.

Did this actually work in a cold start scenario? That is, you start Spotify from a device that's not already playing?



> I wonder if this is related, but at the same time this started happening, when I cast to a Chromecast speaker group, even from the Spotify desktop app, the state of the related Chromecast devices is not updated properly in Home Assistant.. all the devices in the group show `idle` as their state, instead of showing playing, and the details of the stream. Seems Google adjusted something in speaker groups in Google Home as well - can anyone else confirm this behaviour? I don't see any related issues for Cast devices, but it might be related to this same issue.

I didn't have this problem for other casting devices. 


Although I'm not a maintainer, I simply don't see how this problem gets fixed without changes to the Spotify API. Looks like devices are only shown in the API if "active" via Spotify. So even playing/casting other media doesn't make devices show in the API.

**Comment by Banthaf0dder** [comment]
> Although I'm not a maintainer, I simply don't see how this problem gets fixed without changes to the Spotify API. Looks like devices are only shown in the API if "active" via Spotify. So even playing/casting other media doesn't make devices show in the API.

It's a bit crazy how many people here don't understand the purpose of Spotcast. The Spotify API has always behaved this way with google cast devices and this is the entire purpose of Spotcast to begin with.

**Comment by swever826** [comment]
> How does this project solve it?
> https://github.com/music-assistant/hass-music-assistant
> 
> I guess since it requires a server that is always running it is always aware of what cast Devices are available? 
> Tested and I can cast Spotify if i use it. 

From what I understood, that project downloads the music from Spotify and sends it to your smart speaker in real-time. Since it sends the music locally, it doesn't need Spotify to know that your cast devices exist. I have been testing it and it works pretty well so far.

**Comment by fcusson** [comment]
> Although I'm not a maintainer, I simply don't see how this problem gets fixed without changes to the Spotify API. Looks like devices are only shown in the API if "active" via Spotify. So even playing/casting other media doesn't make devices show in the API.

That's why the first step is registering the speaker to the Spotify App in Chromecast system.

I though, by error, that the new problem was due to spotify changing there API, but the change in response is actually from the pychromecast library, the device I'd missing is the Chromecast device Id, not Spotify.

I'm currently exploring step by step where the system is breaking and that seems to be in the app registration problem.

Just to tamper expectations, Im just getting back from vacawand we have a new hire I have to train at work this week, so I might not have a tone of time. Trying to debug as much as possible, but my personal coding time is currently limited.

**Comment by TheFes** [comment]
Well, at least that makes it solvable! Which is good news!

**Comment by GSzabados** [comment]
> I though, by error, that the new problem was due to spotify changing there API, but the change in response is actually from the pychromecast library, the device I'd missing is the Chromecast device Id, not Spotify.

I don't really understand the way how the app registration can be faulty by pychromecast, when there wasn't any changes on that side. The only thing which is changing is the Spotify app on the cast device. The library version a few days ago was 5.30.3, but today is already 5.30.6.

Clearly the device does not send the `deviceID` in the `getInfoResponse`, when the connection initiated from Spotcast. I looked at the webplayer [js](https://open.spotifycdn.com/cdn/build/web-player/web-player.8a34890e.js), and it has some other way to get the `deviceID`, but I cannot really figure out what is the `getCastDevice` does.

A snippet from that code: `((e,t)=>{var n,i;const a=e.getCastDevice(),s={remoteName:a.friendlyName,deviceID:aU(a.friendlyName),deviceAPI_isGroup:a.capabilities.includes(null===(n=chrome)||void 0===n||null===(i=n.cast)||void 0===i?void 0:i.Capability.MULTIZONE_GROUP)};e.sendMessage(tU,{type:"getInfo",payload:s}),sU(t,{step:"message_from_sender"})})(i,n)}`

The rest of the process is the same as in the spotify_controller.py, as grab `accesstoken` by using the `deviceID` and take control of the cast device with that.

**Comment by GSzabados** [comment]
> the device I'd missing is the Chromecast device Id, not Spotify.

And just to confirm, the deviceID missing from the `getInfoResponse` message is the Spotify deviceID, which shows up in the `https://api.spotify.com/v1/me/player/devices` as well.

**Comment by davidruigrok** [comment]
> I though, by error, that the new problem was due to spotify changing there API, but the change in response is actually from the pychromecast library, the device I'd missing is the Chromecast device Id, not Spotify.

Digging a bit deeper, shows the `deviceID` is actually no longer present in the response message from Spotify API:
``` 
protocol_version: CASTV2_1_0
source_id: "0443...."
destination_id: "sender-0"
namespace: "urn:x-cast:com.spotify.chromecast.secure.v1"
payload_type: STRING
payload_utf8: "{\"type\":\"getInfoResponse\",\"payload\":{\"version\":\"2.9.0\",\"publicKey\":\"empty\",\"remoteName\":\"Spotify on Cast\",\"deviceType\":\"cast_audio\",\"brandDisplayName\":\"google\",\"modelDisplayName\":\"Chromecast_Audio\",\"libraryVersion\":\"5.30.3\",\"resolverVersion\":\"1\",\"groupStatus\":\"NONE\",\"deviceAPI_isGroup\":false,\"tokenType\":\"accesstoken\",\"clientID\":\"...\",\"productID\":0,\"scope\":\"streaming\",\"availability\":\"\",\"spotifyError\":0,\"status\":101,\"statusString\":\"OK\"}}"
```
This is the message received from socket in `_read_message()` on `socket_client.py` in `pychromecast`.
But when I am trying to do the same for a chromecast which is already playing spotify there suddenly is a `deviceID` in the response :man_shrugging: :
```
protocol_version: CASTV2_1_0
source_id: "ae9..."
destination_id: "sender-0"
namespace: "urn:x-cast:com.spotify.chromecast.secure.v1"
payload_type: STRING
payload_utf8: "{\"type\":\"getInfoResponse\",\"payload\":{\"version\":\"2.9.0\",\"deviceID\":\"fffc...\",\"publicKey\":\"empty\",\"remoteName\":\"Opkamer\",\"deviceType\":\"cast_audio\",\"brandDisplayName\":\"google\",\"modelDisplayName\":\"Chromecast_Audio\",\"libraryVersion\":\"5.30.6\",\"resolverVersion\":\"1\",\"groupStatus\":\"NONE\",\"deviceAPI_isGroup\":false,\"tokenType\":\"accesstoken\",\"clientID\":\"...\",\"productID\":0,\"scope\":\"streaming\",\"availability\":\"\",\"spotifyError\":0,\"status\":101,\"statusString\":\"OK\"}}"
```

**Comment by GSzabados** [comment]
> Digging a bit deeper, shows the `deviceID` is actually no longer present in the response message from Spotify API:

Can you try to compose a message to the device according the webplayer's method? I am a bit programming handicapped... 😉

{type:"getInfo",
payload: {
remoteName:a.friendlyName,
deviceID:aU(a.friendlyName),
deviceAPI_isGroup:a.capabilities.includes(null===(n=chrome)||void 0===n||null===(i=n.cast)||void 0===i?void 0:i.Capability.MULTIZONE_GROUP)
}
}

The values for friendlyName, etc... comes from the getCastDevice function from the Cast web sender:

https://developers.google.com/cast/docs/reference/web_sender/cast.framework.CastSession#getCastDevice 

I am still trying to figure out what aU(a.friendlyName) does.

**Comment by GSzabados** [comment]
> I'm currently exploring step by step where the system is breaking and that seems to be in the app registration problem.

If it is really an app registration problem, what can be. The source of a change here might be some not set options for the app.

In reference to the web player:

`s.setOptions({ receiverApplicationId: XM.cast.appId, autoJoinPolicy: "page_scoped", androidReceiverCompatible: n }`

From previous versions of web player (thanks to WebArchive) the setOptions requirement was only the AppID.

**Comment by davidruigrok** [comment]
Currently seems to send the following payload to launch the spotify application:
```
{'type': 'LAUNCH', 'appId': 'CC32E753'}
```

**Comment by vekexasia** [comment]
subscribing to follow the issue. As I'm affected as well.

**Comment by strandaster** [comment]
Please use the subscribe button in the notification area. This helps to have a clean discussion for solving the issue.
Thanks!

**Comment by davidruigrok** [comment]
> I am still trying to figure out what `aU(a.friendlyName)` does.

Had some time to dig in a bit more and I think the friendly name gets converted to a md5 hash which is used as the `deviceID` after that. For example, I have a chromecast with the `friendlyName` _Opkamer_. The corresponding spotify `deviceID` is `a405a64e9f12009792e0c862f6ebe5e0`. The md5 hash of _Opkamer_ is also `a405a64e9f12009792e0c862f6ebe5e0` :exploding_head: 

In the end, the `aU(a.friendlyName)`  ends up here in the web-player.js (where `e` in this case is _Opkamer_):
```
return function(e) {
   return new Md5(!0).update(e)[t]()
}
```

Did some quick testing and it does seem to work when I also send `payload` with `remoteName`, `deviceID`, and `deviceAPI_isGroup` on `getInfo`.

Long story short, the `deviceID` seems to be the md5 hash of the `friendly_name` of the device. 
I will do some additional testing and create PR when I have some time, probably after the weekend...

**Comment by GSzabados** [comment]
> Did some quick testing and it does seem to work when I also send `payload` with `remoteName`, `deviceID`, and `deviceAPI_isGroup` on `getInfo`.
> 
> Long story short, the `deviceID` seems to be the md5 hash of the `friendly_name` of the device. I will do some additional testing and create PR when I have some time, probably after the weekend...

Thanks for digging into that deeper! So in the new way the web player defines the deviceID for the device and not the app on the device? Interesting!

It suggests me, that this might be a solution to make sure the app is started on the right device and not to confuse a rouge `getInfoResponse` from another device with.

**Comment by davidruigrok** [comment]
Created PR https://github.com/fondberg/spotcast/pull/406 which should fix the missing `deviceID` issue. Had on time to test it within Home Assistant yet. Feel free to do so, as I do not have much time this weekend.

@fcusson Would you be able to test these changes and see if this would fix it?

```
Thanks for digging into that deeper! So in the new way the web player defines the deviceID for the device and not the app on the device? Interesting!
```

Not sure, but I guess this way Spotify has more possibilities whenever they would like to change the way how the `deviceID` is constructed without a app update.

**Comment by kartemov** [comment]
Confirmed the fix is working. Thank you all!

**Comment by techtim89** [comment]
YES!!!!  Spotcast v3.7.1 just dropped in HACS.  Updated and all is working again!  WOOHOO!!  Thank you all who worded to get us all back up and working.

**Comment by andyrowe247** [comment]
Working for me!

Legend! Many thanks for fixing this very important integration.

👍👍👍👍

**Comment by jboesh** [comment]
Thanks all. Working again!

**Comment by 1ntroduc3** [comment]
Only the Spotify playlist card from fondberg now doesn't work anymore. Keeps loading

**Comment by GSzabados** [comment]
> Keeps loading

Works for me without any issues. Try to reload the UI.

**Comment by aliaghil** [comment]
works well for me, thanks a lot.

**Comment by teek541** [comment]
Thanks for fixing this!  I had to redo how spotcast was being called, but got it working even better now.

![image](https://github.com/fondberg/spotcast/assets/45326308/7d7e4791-32f7-4054-afcd-435858d2f1a0)

**Comment by quincarter** [comment]
> Thanks for fixing this!  I had to redo how spotcast was being called, but got it working even better now.
> 
> ![image](https://github.com/fondberg/spotcast/assets/45326308/7d7e4791-32f7-4054-afcd-435858d2f1a0)
> 

How did you do the card on the right? Mind sharing?

**Comment by teek541** [comment]
It's a combination of a few cards, input selects and input booleans, and node red code.

The top input boolean toggle allows me to "send" the variables to call the spotcast service.  I have 2 accounts at home, my wife's and mine.  If she is playing music, and we want to change what it's casting to, I need to select her account before I select a new speaker.  Node red will then see it as a previously playing spotify media player and not start the playlist over and just continue playback.  So if I had it trigger as soon as you made any selection it could affect that.  That being said, if we have a party going on, and someone wants to change the playlist, if the input boolean is toggled on (which it stays on unless all players are idle), it sends the command right away.

I have conditional cards that display if a speaker group is selected.  That way you can adjust all of the speakers in the group together.  But the collapsible card will expand out the speakers currently playing in the group to adjust them automatically.

The "now playing" on the left are conditional cards, but I'd like to have this be based on what account is selected in the account input_select later.  I just haven't messed with that yet.

Dashboard YAML:
   - title: Music
    path: music
    icon: mdi:music
    subview: false
    type: panel
    theme: ios-dark-mode-blue-red-alternative
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: conditional
            conditions:
              - entity: media_player.spotify_[ACCOUNT1]
                state_not: idle
            card:
              type: media-control
              entity: edia_player.spotify_[ACCOUNT1]
          - type: conditional
            conditions:
              - entity: edia_player.spotify_[ACCOUNT2]
                state_not: idle
            card:
              type: media-control
              entity: edia_player.spotify_[ACCOUNT2]
          - type: vertical-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: custom:mushroom-chips-card
                    chips:
                      - type: template
                        tap_action:
                          action: toggle
                        entity: input_boolean.start_spotify
                        icon: mdi:spotify
                        icon_color: '{{ ''green'' if states(entity) == ''on'' else ''grey'' }}'
                    alignment: center
                  - type: entities
                    entities:
                      - entity: input_select.speakers
                      - entity: input_select.music_playlist
                      - entity: input_select.spotify_account
                        name: Spotify Account
                  - type: conditional
                    conditions:
                      - entity: media_player.[Speaker_Group1]
                        state: playing
                    card:
                      type: custom:mushroom-media-player-card
                      entity: media_player.[Speaker_Group1]
                      volume_controls:
                        - volume_mute
                        - volume_set
                        - volume_buttons
                      show_volume_level: true
                  - type: conditional
                    conditions:
                      - entity: media_player.[Speaker_Group2]
                        state: playing
                    card:
                      type: custom:mushroom-media-player-card
                      volume_controls:
                        - volume_mute
                        - volume_set
                        - volume_buttons
                      show_volume_level: true
                      entity: media_player.[Speaker_Group2]
                  - type: custom:collapsable-cards
                    title: Speaker Volumes
                    defaultOpen: false
                    cards:
                      - type: custom:auto-entities
                        card:
                          type: grid
                          columns: 1
                          square: false
                        card_param: cards
                        filter:
                          template: |-
                            {% for state in states.media_player -%}
                              {%- if state.attributes.device_class == 'speaker' and state.state in ['playing', 'paused']
                                 and "speakers" not in state.attributes.friendly_name|lower 
                                 and "Living Room TV" not in state.attributes.friendly_name -%}
                              {{
                                {
                                'entity': state.entity_id,
                                'type': 'custom:mushroom-media-player-card',
                                'primary_info': 'name',
                                'use_media_info': false,
                                'show_volume_level': true,
                                'volume_controls':
                                  '- volume_mute'
                                  '- volume_set'
                                  '- volume_buttons',
                                'collapsible_controls': true
                                }
                              }},
                              {%- endif -%}
                            {%- endfor %}
                        exclude: []
                        show_empty: true


![image](https://github.com/fondberg/spotcast/assets/45326308/22e5362a-1a14-429e-873b-fb8f1ebb1b75)
Data for Resuming Playback
{"device_name":device_name,"force_playback":true,"account":account}

Data for Start Spotcast
{"device_name":device_name,"force_playback":true,"uri":uri,"random_song":true,"shuffle":true,"account":account}


I currently have a flow variable for "resume" which allows me to determine when I'm just changing speakers vs when it needs to start a whole new spotcast service call.



Hope this helps.

**Comment by quincarter** [comment]
Epic. Thanks for sharing @teek541 !
